version: '3'
services:
  database:
    image: "postgres"
    ports:
      - "5432:5434"
    environment:
      - POSTGRES_PASSWORD=password

  web:
    image: writerpad
    ports:
      - "8080:8080"
